services:
  sql-server:
    image: mssql-hack:latest
    container_name: sql-server-1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Q1w2e3r4
      - SVC_PASS=Q1w2e3r4
    ports:
      - "1433:1433"
    networks:
      - default
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq-1
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
  
networks:
  default:
    driver: bridge