x-common-environment: &common-environment
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: Server=sql-server,1433;Database=medschedule;User Id=migration_user;Password=Q1w2e3r4;TrustServerCertificate=True;MultipleActiveResultSets=true;
  ConnectionStrings__DatabaseDllConnection: Server=sql-server;Database=medschedule;User Id=migration_user;Password=Q1w2e3r4;TrustServerCertificate=True;
  ProducerSettings__Host: rabbit-mq

services:
  sql-server:
    image: mssql-hack:latest
    container_name: sql-server-1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Q1w2e3r4
      - SVC_PASS=Q1w2e3r4
    ports:
      - "1433:1433"
    networks:
      - default
  rabbit-mq:
    image: rabbitmq:3-management
    container_name: rabbit-mq-1
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - default
  schedule-app:
    image: schedule-app
    container_name: schedule-app-1
    ports:
      - "80:8080"
    environment:
      <<: *common-environment
    depends_on:
      - sql-server
    entrypoint: ["./wait-for-it.sh", "sql-server:1433", "--", "dotnet", "Fiap.Health.Med.Schedule.Manager.Api.dll"]
    networks:
      - default
  schedule-worker:
    image: schedule-worker
    container_name: schedule-worker-1
    environment:
      ConsumerSettings__Host: rabbit-mq
      <<: *common-environment
    depends_on:
      - sql-server
    entrypoint: ["./wait-for-it.sh", "sql-server:1433", "--","./wait-for-it.sh", "rabbit-mq:5672", "--", "dotnet", "Fiap.Health.Med.Schedule.Manager.Worker.dll"]
    networks:
      - default
  user-app:
    image: user-app
    container_name: user-app-1
    ports:
      - "81:8080"
    environment:
      <<: *common-environment
    depends_on:
      - sql-server
    entrypoint: ["./wait-for-it.sh", "sql-server:1433", "--", "dotnet", "Fiap.Health.Med.User.Manager.Api.dll"]
    networks:
      - default
networks:
  default:
    driver: bridge