trigger:
  branches:
    include:
      - feat/kubernetes

  paths:
    include:
      - sql-server/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  dockerRegistryServiceConnection: $(_dockerRegistryServiceConnection)
  imageRepository: $(_imageRepository)
  containerRegistry: $(_containerRegistry)
  dockerfilePath: $(System.DefaultWorkingDirectory)/sql-server/Dockerfile
  kubernetesServiceEndpoint: $(_kubernetesServiceEndpoint)
  k8sNamespace: $(_k8sNamespace)

stages:

- stage: Build
  displayName: Build and push stage
  jobs:
  - job: BuildSqlImage
    displayName: Build SQL Server Docker Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Show ws files.
          echo $(ls)

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(_dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy Stage
  jobs:
  - job: DeployDatabase
    displayName: Deploy Sql Server to AKS
    steps:
      - script: ls $(System.DefaultWorkingDirectory)/sql-server
        displayName: "Check folder sql-server"

      - script: |
          cat $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
          sed -i 's/PLACEHOLDER_NAMESPACE/$(k8sNamespace)/g' $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
          sed -i 's/PLACEHOLDER_CONTAINER_REGISTRY/$(containerRegistry)/g' $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
          sed -i 's/PLACEHOLDER_IMAGE_REPOSITORY/$(imageRepository)/g' $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
          cat $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
        displayName: 'Replace variables in YAML'
      - script: cat $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml
        displayName: Show k8s.dev.yaml
      - task: kubernetes@1
        displayName: "Apply Deployment YAML"
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: $(kubernetesServiceEndpoint)
          namespace: $(k8sNamespace)
          command: apply
          arguments: -f $(System.DefaultWorkingDirectory)/sql-server/k8s.dev.yaml